#!/usr/bin/env python3
"""Expand WC 1986–2002 to full (or near-full) tournament coverage."""
import json, random, os

OLD_PATH = os.path.join(os.path.dirname(__file__), 'src/data/players_wc_old.json')
TARGET = 16

AVG = {
    'GK':  {'pac':50,'sho':10,'pas':50,'dri':50,'def':60,'phy':70},
    'CB':  {'pac':55,'sho':30,'pas':55,'dri':50,'def':75,'phy':75},
    'LB':  {'pac':70,'sho':35,'pas':60,'dri':60,'def':65,'phy':65},
    'RB':  {'pac':70,'sho':35,'pas':60,'dri':60,'def':65,'phy':65},
    'LWB': {'pac':72,'sho':40,'pas':62,'dri':62,'def':60,'phy':65},
    'RWB': {'pac':72,'sho':40,'pas':62,'dri':62,'def':60,'phy':65},
    'CDM': {'pac':60,'sho':40,'pas':65,'dri':60,'def':70,'phy':72},
    'CM':  {'pac':62,'sho':55,'pas':72,'dri':65,'def':58,'phy':65},
    'CAM': {'pac':68,'sho':65,'pas':75,'dri':75,'def':40,'phy':60},
    'RM':  {'pac':75,'sho':62,'pas':68,'dri':72,'def':42,'phy':62},
    'LM':  {'pac':75,'sho':62,'pas':68,'dri':72,'def':42,'phy':62},
    'RW':  {'pac':78,'sho':68,'pas':65,'dri':78,'def':35,'phy':60},
    'LW':  {'pac':78,'sho':68,'pas':65,'dri':78,'def':35,'phy':60},
    'ST':  {'pac':70,'sho':78,'pas':58,'dri':68,'def':30,'phy':72},
}

def make(name, positions, overall, tournament='WC', nation=None, year=None):
    pos = positions[0]
    base = AVG.get(pos, AVG['CM'])
    delta = overall - 75
    stats = {k: min(99, max(40, v + delta + random.randint(-3, 3))) for k, v in base.items()}
    return {'name': name, 'nation': nation, 'year': year,
            'positions': positions, 'overall': overall, 'tournament': tournament, **stats}

def add_nations(path, tournament, squads):
    data = json.load(open(path))
    existing = {(p['name'], p['nation'], p['year']) for p in data}
    counts = {}
    for p in data:
        k = (p['nation'], p['year'])
        counts[k] = counts.get(k, 0) + 1
    added = 0
    for nation, year, players in squads:
        k = (nation, year)
        cur = counts.get(k, 0)
        for name, pos, ovr in players:
            if cur >= TARGET:
                break
            if (name, nation, year) not in existing:
                data.append(make(name, pos, ovr, tournament, nation, year))
                existing.add((name, nation, year))
                cur += 1
                added += 1
        counts[k] = cur
    json.dump(data, open(path, 'w'), ensure_ascii=False, indent=2)
    print(f'Added {added} players. Total: {len(data)}')

random.seed(42)

SQUADS = [
    # =========================================================
    # WC 1986  (24 teams; already have: Argentina, Belgium,
    #           Brazil, England, France, Mexico, Spain, West Germany)
    # =========================================================
    ('Bulgaria', 1986, [
        ('Borislav Mikhailov', ['GK'], 80),
        ('Plamen Nikolov', ['GK'], 74),
        ('Trifon Ivanov', ['CB'], 79),
        ('Aleksandar Shalamanov', ['CB'], 77),
        ('Nasko Sirakov', ['RW'], 81),
        ('Georgi Georgiev', ['CM'], 77),
        ('Stoicho Mladenov', ['CM'], 78),
        ('Emil Spasov', ['ST'], 78),
        ('Petar Jeliazkov', ['LB'], 76),
        ('Stefan Markov', ['CDM'], 76),
        ('Georgi Dimitrov', ['RB'], 75),
        ('Venelin Valkov', ['ST'], 76),
    ]),
    ('Canada', 1986, [
        ('Tino Lettieri', ['GK'], 74),
        ('Randy Samuel', ['CB'], 74),
        ('Bruce Wilson', ['LB'], 73),
        ('Bob Lenarduzzi', ['CB'], 74),
        ('Paul James', ['CM'], 73),
        ('Dale Mitchell', ['LW'], 74),
        ('Igor Vrablic', ['RW'], 73),
        ('Carl Valentine', ['RM'], 73),
        ('David Norman', ['CDM'], 72),
        ('George Pakos', ['ST'], 73),
        ('Gerry Gray', ['CB'], 72),
        ('John Catliff', ['ST'], 72),
    ]),
    ('Denmark', 1986, [
        ('Ole Qvist', ['GK'], 79),
        ('Peter Schmeichel', ['GK'], 78),  # 22, backup
        ('Ivan Nielsen', ['CB'], 80),
        ('Søren Busk', ['CB'], 79),
        ('Morten Olsen', ['CDM'], 83),
        ('Michael Laudrup', ['CAM'], 88),
        ('Preben Elkjær', ['ST'], 86),
        ('Sören Lerby', ['CM'], 83),
        ('Jan Molby', ['CM'], 82),
        ('Klaus Berggreen', ['RW'], 79),
        ('Frank Arnesen', ['CM'], 81),
        ('Henrik Andersen', ['LB'], 76),
        ('Lars Olsen', ['CB'], 79),
        ('Jesper Olsen', ['LM'], 80),
        ('John Sivebæk', ['RB'], 78),
        ('Michael Laudrup', ['CAM'], 88),
    ]),
    ('Hungary', 1986, [
        ('Péter Disztl', ['GK'], 79),
        ('Lajos Détári', ['CAM'], 83),
        ('Tibor Nyilasi', ['CM'], 82),
        ('György Bognár', ['ST'], 79),
        ('Imre Garaba', ['CDM'], 79),
        ('Pál Dárdai', ['CM'], 77),
        ('Sándor Sallai', ['LB'], 76),
        ('Péter Roth', ['CB'], 77),
        ('József Kiprich', ['ST'], 78),
        ('Zsolt Kismányoky', ['RM'], 76),
        ('Antal Nagy', ['CB'], 76),
        ('Ferenc Mészáros', ['RB'], 75),
    ]),
    ('Iraq', 1986, [
        ('Basil Gorgis', ['GK'], 74),
        ('Ahmed Radhi', ['ST'], 77),
        ('Hussein Saeed', ['ST'], 78),
        ('Faris Allawi', ['CM'], 75),
        ('Kais Khalef', ['CDM'], 74),
        ('Ali Hisham', ['CB'], 74),
        ('Hadi Ahmed', ['RB'], 73),
        ('Waleed Mustafa', ['LB'], 73),
        ('Adnan Dirjal', ['RM'], 74),
        ('Hamid Hashem', ['CB'], 73),
    ]),
    ('Italy', 1986, [
        ('Walter Zenga', ['GK'], 82),
        ('Giovanni Galli', ['GK'], 79),
        ('Franco Baresi', ['CB'], 88),
        ('Gaetano Scirea', ['CB'], 86),
        ('Antonio Cabrini', ['LB'], 82),
        ('Pietro Vierchowod', ['CB'], 81),
        ('Claudio Gentile', ['CB'], 79),
        ('Bruno Conti', ['RM'], 82),
        ('Marco Tardelli', ['CM'], 82),
        ('Alessandro Altobelli', ['ST'], 83),
        ('Gianluca Vialli', ['ST'], 80),
        ('Carlo Ancelotti', ['CM'], 81),
        ('Giuseppe De Napoli', ['CDM'], 79),
        ('Aldo Serena', ['ST'], 77),
        ('Antonio Di Gennaro', ['CM'], 78),
        ('Salvatore Bagni', ['CDM'], 78),
    ]),
    ('Morocco', 1986, [
        ('Zaki', ['GK'], 81),
        ('Aziz Bouderbala', ['RW'], 80),
        ('Mustapha El Haddaoui', ['ST'], 79),
        ('Abdel Majid Dolmy', ['CAM'], 78),
        ('Mohamed Timoumi', ['CM'], 78),
        ('Nasser Diouri', ['CB'], 76),
        ('Boujemaa Benacer', ['LB'], 75),
        ('Abdelkader El Hadrioui', ['CB'], 76),
        ('Mustafa Hadji (Sr)', ['RM'], 75),
        ('Mohammed Chaouch', ['ST'], 76),
        ('Lahcen Abrami', ['CDM'], 75),
        ('Said Aouita', ['RB'], 74),
    ]),
    ('Paraguay', 1986, [
        ('Roberto Fernández', ['GK'], 79),
        ('Julio César Romero', ['CAM'], 83),
        ('Romerito', ['LW'], 82),
        ('Carlos Gamarra', ['CB'], 76),  # very young
        ('Emilio Aceval', ['CB'], 78),
        ('Carlos Caceres', ['ST'], 78),
        ('Carlos Alonso', ['CM'], 77),
        ('Adolfino Cañete', ['LB'], 76),
        ('Sabino Solis', ['RB'], 75),
        ('Orlando Fernandez', ['CDM'], 76),
        ('Fernando Chalco', ['RM'], 75),
        ('Juan Ramirez', ['ST'], 76),
    ]),
    ('Poland', 1986, [
        ('Józef Młynarczyk', ['GK'], 79),
        ('Zbigniew Boniek', ['RM'], 86),
        ('Andrzej Buncol', ['CM'], 80),
        ('Dariusz Dziekanowski', ['ST'], 81),
        ('Roman Wójcicki', ['CDM'], 78),
        ('Marek Ostrowski', ['CB'], 78),
        ('Waldemar Matysik', ['CB'], 77),
        ('Włodzimierz Ciołek', ['LB'], 77),
        ('Jan Karas', ['RB'], 76),
        ('Bogusław Łazur', ['ST'], 77),
        ('Ryszard Tarasiewicz', ['LM'], 77),
        ('Grzegorz Lato', ['RW'], 79),  # veteran
    ]),
    ('Portugal', 1986, [
        ('Manuel Bento', ['GK'], 79),
        ('Fernando Chalana', ['LM'], 82),
        ('Diamantino Miranda', ['RW'], 80),
        ('João Pinto', ['ST'], 79),
        ('Rui Barros', ['CM'], 78),
        ('Frederico Tenreiro', ['CB'], 76),
        ('Álvaro Magalhães', ['LB'], 77),
        ('Jaime Pacheco', ['CDM'], 78),
        ('Nené', ['CAM'], 79),
        ('António Veloso', ['CB'], 78),
        ('Carlos Manuel', ['CM'], 78),
        ('Inácio', ['CB'], 77),
    ]),
    ('Scotland', 1986, [
        ('Jim Leighton', ['GK'], 81),
        ('Willie Miller', ['CB'], 82),
        ('Alex McLeish', ['CB'], 81),
        ('Gordon Strachan', ['RM'], 83),
        ('Graeme Souness', ['CM'], 84),
        ('Steve Nicol', ['RB'], 81),
        ('Roy Aitken', ['CDM'], 80),
        ('Charlie Nicholas', ['ST'], 80),
        ('Mo Johnston', ['ST'], 80),
        ('Maurice Malpas', ['LB'], 79),
        ('Paul McStay', ['CM'], 82),
        ('Alan Hansen', ['CB'], 84),
        ('Steve Archibald', ['ST'], 79),
        ('Kenny Dalglish', ['CAM'], 84),
        ('Davie Cooper', ['LW'], 80),
        ('Jim Bett', ['CM'], 78),
    ]),
    ('South Korea', 1986, [
        ('Oh Yeon-kyo', ['GK'], 75),
        ('Huh Jung-moo', ['CM'], 80),
        ('Park Chang-sun', ['ST'], 78),
        ('Choi Soon-ho', ['ST'], 77),
        ('Kim Joo-sung', ['CB'], 77),
        ('Choi Kang-hee', ['CM'], 76),
        ('Kim Jong-boo', ['CB'], 75),
        ('Park Kyung-hoon', ['LB'], 74),
        ('Cho Kwang-rae', ['CDM'], 75),
        ('Lee Tae-ho', ['RW'], 74),
        ('Kim Pyung-seok', ['RB'], 74),
        ('Byun Byung-joo', ['LM'], 74),
    ]),
    ('Soviet Union', 1986, [
        ('Rinat Dasayev', ['GK'], 84),
        ('Igor Belanov', ['ST'], 83),
        ('Alexander Zavarov', ['CAM'], 82),
        ('Vasili Rats', ['LB'], 81),
        ('Sergei Litovchenko', ['CM'], 81),
        ('Oleg Kuznetsov', ['CB'], 82),
        ('Alexander Chivadze', ['CB'], 81),
        ('Andriy Bal', ['CB'], 79),
        ('Gennadiy Moroz', ['RM'], 77),
        ('Sergei Rodionov', ['ST'], 79),
        ('Genadiy Lytovchenko', ['CM'], 79),
        ('Vagiz Khidiyatullin', ['CDM'], 80),
        ('Sergei Aleinikov', ['CM'], 80),
        ('Alexander Bubnov', ['CB'], 78),
        ('Lariy Bertish', ['RB'], 76),
        ('Oleg Blokhin', ['LW'], 81),
    ]),
    ('Uruguay', 1986, [
        ('Fernando Álvez', ['GK'], 79),
        ('Enzo Francescoli', ['CAM'], 86),
        ('Hugo De León', ['CB'], 82),
        ('Carlos Aguilera', ['LW'], 80),
        ('Rubén Sosa', ['LW'], 81),
        ('Daniel Fonseca', ['ST'], 80),
        ('Nelson Gutiérrez', ['CM'], 79),
        ('Wilmar Cabrera', ['CDM'], 79),
        ('Jorge Barrios', ['RW'], 77),
        ('José Pintos Saldanha', ['LB'], 76),
        ('Miguel Polilla Da Silva', ['CM'], 78),
        ('Venancio Ramos', ['CB'], 77),
        ('Jorge Bossio', ['RB'], 76),
        ('Víctor Diogo', ['ST'], 78),
        ('Eduardo Acevedo', ['CM'], 77),
        ('Antonio Alzamendi', ['ST'], 79),
    ]),
    ('Algeria', 1986, [
        ('Mehdi Cerbah', ['GK'], 75),
        ('Lakhdar Belloumi', ['CAM'], 81),
        ('Djamel Menad', ['ST'], 79),
        ('Rabah Madjer', ['LW'], 82),
        ('Hocine Yahi', ['CB'], 76),
        ('Mahmoud Guendouz', ['CDM'], 76),
        ('Abdel-Hamid Semmane', ['CM'], 75),
        ('Fodil Megharia', ['CB'], 75),
        ('Salah Assad', ['LB'], 74),
        ('Salim Mellouk', ['RM'], 76),
        ('Noureddine Kourichi', ['RB'], 74),
        ('Moussa Saïb', ['CM'], 76),
    ]),
    ('Northern Ireland', 1986, [
        ('Pat Jennings', ['GK'], 79),  # final tournament at 41
        ('Norman Whiteside', ['CM'], 82),
        ('Mal Donaghy', ['CB'], 78),
        ('Martin O\'Neill', ['CM'], 79),
        ('Gerry Armstrong', ['ST'], 78),
        ('Billy Hamilton', ['ST'], 77),
        ('Jimmy Quinn', ['ST'], 76),
        ('John McClelland', ['CB'], 77),
        ('David McCreery', ['CDM'], 76),
        ('Jimmy Nicholl', ['RB'], 77),
        ('Sammy McIlroy', ['CM'], 79),
        ('Ian Stewart', ['LM'], 75),
    ]),

    # =========================================================
    # WC 1990  (24 teams; already have: Argentina, Cameroon,
    #           England, Italy, West Germany, Yugoslavia)
    # =========================================================
    ('Austria', 1990, [
        ('Klaus Lindenberger', ['GK'], 78),
        ('Toni Polster', ['ST'], 83),
        ('Andreas Herzog', ['CAM'], 82),
        ('Herbert Prohaska', ['CM'], 79),
        ('Gerhard Rodax', ['ST'], 79),
        ('Ernst Aigner', ['CDM'], 77),
        ('Robert Sara', ['CB'], 76),
        ('Bruno Pezzey', ['CB'], 78),
        ('Heimo Pfeifenberger', ['LW'], 78),
        ('Karl Brauneder', ['LB'], 76),
        ('Wolfgang Feiersinger', ['RB'], 77),
        ('Reinhard Kienast', ['RM'], 76),
    ]),
    ('Belgium', 1990, [
        ('Michel Preud\'homme', ['GK'], 84),
        ('Enzo Scifo', ['CAM'], 84),
        ('Jan Ceulemans', ['ST'], 82),
        ('Marc Degryse', ['RW'], 81),
        ('Eric Gerets', ['RB'], 79),
        ('Philippe Albert', ['CB'], 81),
        ('Stéphane Demol', ['CB'], 78),
        ('Franky Van Der Elst', ['CM'], 79),
        ('Leo Clijsters', ['CDM'], 78),
        ('Marc Wilmots', ['CDM'], 79),
        ('Luc Nilis', ['ST'], 78),
        ('Vincenzo Scifo', ['CM'], 79),
        ('Graef', ['LB'], 75),
        ('Grün', ['CB'], 78),
        ('Weber', ['LM'], 76),
        ('Versavel', ['RB'], 75),
    ]),
    ('Brazil', 1990, [
        ('Taffarel', ['GK'], 84),
        ('Branco', ['LB'], 83),
        ('Aldair', ['CB'], 84),
        ('Mauro Galvão', ['CB'], 81),
        ('Mozer', ['CB'], 80),
        ('Dunga', ['CDM'], 84),
        ('Bebeto', ['ST'], 83),
        ('Careca', ['ST'], 86),
        ('Müller', ['ST'], 83),
        ('Valdo', ['CM'], 81),
        ('Mazinho', ['CM'], 79),
        ('Ricardo Rocha', ['CB'], 79),
        ('Tita', ['LW'], 78),
        ('Alemão', ['CM'], 80),
        ('Paulo Silas', ['RM'], 77),
        ('Acácio', ['GK'], 76),
    ]),
    ('Colombia', 1990, [
        ('René Higuita', ['GK'], 83),
        ('Carlos Valderrama', ['CM'], 87),
        ('Freddy Rincón', ['CM'], 83),
        ('Adolfo Valencia', ['ST'], 81),
        ('Arnoldo Iguarán', ['ST'], 80),
        ('Leonel Álvarez', ['CDM'], 79),
        ('Luis Carlos Perea', ['CB'], 81),
        ('Andrés Escobar', ['CB'], 82),
        ('Alberto García Aspe', ['LB'], 78),
        ('Alexis García', ['RB'], 78),
        ('Gabriel Jaime Gómez', ['RM'], 79),
        ('Hernán Gaviria', ['LW'], 78),
    ]),
    ('Costa Rica', 1990, [
        ('Luis Gabelo Conejo', ['GK'], 79),
        ('Hernán Medford', ['RW'], 79),
        ('Juan Cayasso', ['LW'], 77),
        ('Róger Flores', ['ST'], 77),
        ('Ronald González', ['CB'], 76),
        ('Mauricio Montero', ['CB'], 76),
        ('Carlos Luis Marín', ['LB'], 75),
        ('Claudio Jara', ['RB'], 75),
        ('Gilberto Martínez', ['CDM'], 75),
        ('Julio Arroyo', ['CM'], 74),
        ('Errol McNish', ['ST'], 75),
        ('Guimaraes', ['CM'], 74),
    ]),
    ('Czechoslovakia', 1990, [
        ('Jan Stejskal', ['GK'], 80),
        ('Tomáš Skuhravý', ['ST'], 82),
        ('Luboš Kubík', ['CM'], 81),
        ('Ivan Hašek', ['CM'], 80),
        ('Ján Kocian', ['CB'], 79),
        ('Jozef Chovanec', ['CDM'], 80),
        ('Michal Bílek', ['CAM'], 79),
        ('Peter Liška', ['CB'], 77),
        ('Miroslav Kadlec', ['CB'], 79),
        ('Vladimír Daněk', ['LB'], 76),
        ('Ivan Fiala', ['RB'], 76),
        ('Lubomír Moravčík', ['LM'], 81),
        ('Stanislav Griga', ['ST'], 78),
        ('Pavel Kuka', ['ST'], 79),
        ('Michal Horňák', ['RM'], 76),
        ('Ladislav Pecko', ['GK'], 75),
    ]),
    ('Egypt', 1990, [
        ('Ahmed Shobeir', ['GK'], 78),
        ('Hossam Hassan', ['ST'], 81),
        ('Ibrahim Hassan', ['CM'], 77),
        ('Tarek Diab', ['CM'], 77),
        ('Rabie Yassin', ['RW'], 76),
        ('Magdi Abdelghani', ['CB'], 77),
        ('Youssef Shawky', ['CB'], 76),
        ('Alaa Mubarak', ['LB'], 75),
        ('Hany Ramzy', ['CB'], 79),
        ('Hisham Yakin', ['CDM'], 75),
        ('Ahmed Hossam Mido', ['ST'], 74),
        ('Shawki Gharieb', ['RB'], 74),
    ]),
    ('Ireland', 1990, [
        ('Packie Bonner', ['GK'], 82),
        ('Paul McGrath', ['CB'], 86),
        ('Mick McCarthy', ['CB'], 79),
        ('Kevin Moran', ['CB'], 79),
        ('Steve Staunton', ['LB'], 80),
        ('Ray Houghton', ['CM'], 82),
        ('Andy Townsend', ['CM'], 81),
        ('John Aldridge', ['ST'], 81),
        ('Tony Cascarino', ['ST'], 79),
        ('Kevin Sheedy', ['LM'], 80),
        ('Niall Quinn', ['ST'], 79),
        ('Chris Morris', ['RB'], 77),
        ('John Sheridan', ['CM'], 79),
        ('David O\'Leary', ['CB'], 81),
        ('Frank Stapleton', ['ST'], 78),
        ('Ronnie Whelan', ['CM'], 80),
    ]),
    ('Netherlands', 1990, [
        ('Hans van Breukelen', ['GK'], 83),
        ('Ruud Gullit', ['CAM'], 92),
        ('Marco van Basten', ['ST'], 93),
        ('Frank Rijkaard', ['CDM'], 88),
        ('Ronald Koeman', ['CB'], 89),
        ('Jan Wouters', ['CM'], 82),
        ('Berry van Aerle', ['RB'], 81),
        ('Erwin Koeman', ['RB'], 80),
        ('John van \'t Schip', ['CM'], 82),
        ('Aron Winter', ['CM'], 81),
        ('Wim Kieft', ['ST'], 81),
        ('Frank de Boer', ['CB'], 80),
        ('Rob Witschge', ['LM'], 79),
        ('Adri van Tiggelen', ['LB'], 79),
        ('Richard Witschge', ['CM'], 79),
        ('Stanley Menzo', ['GK'], 78),
    ]),
    ('Romania', 1990, [
        ('Silviu Lung', ['GK'], 79),
        ('Gheorghe Hagi', ['CAM'], 88),
        ('Marius Lăcătuș', ['RW'], 83),
        ('Dan Petrescu', ['RB'], 81),
        ('Florin Răducioiu', ['ST'], 82),
        ('Ioan Sabău', ['CM'], 79),
        ('Gheorghe Popescu', ['CDM'], 84),
        ('Costică Ștefănescu', ['LB'], 76),
        ('Miodrag Belodedici', ['CB'], 81),
        ('Daniel Timofte', ['CM'], 77),
        ('Rodion Cămătaru', ['ST'], 78),
        ('Iosif Rotariu', ['CM'], 78),
        ('Dorin Mateuț', ['LW'], 79),
        ('Gavril Balint', ['CB'], 77),
        ('Adrian Bumbescu', ['CB'], 76),
        ('Bogdan Stelea', ['GK'], 76),
    ]),
    ('Scotland', 1990, [
        ('Jim Leighton', ['GK'], 80),
        ('Roy Aitken', ['CDM'], 79),
        ('Paul McStay', ['CM'], 83),
        ('Stuart McCall', ['CM'], 80),
        ('Maurice Malpas', ['LB'], 79),
        ('Ally McCoist', ['ST'], 82),
        ('Gordon Durie', ['ST'], 80),
        ('Steve Nicol', ['RB'], 80),
        ('Richard Gough', ['CB'], 83),
        ('Alan McInally', ['ST'], 79),
        ('Gary McAllister', ['CM'], 81),
        ('Alex McLeish', ['CB'], 80),
        ('Tom Boyd', ['LB'], 77),
        ('Dave McPherson', ['CB'], 77),
        ('Jim Bett', ['CM'], 77),
        ('Pat Nevin', ['RW'], 79),
    ]),
    ('South Korea', 1990, [
        ('Choi In-young', ['GK'], 77),
        ('Kim Joo-sung', ['CB'], 78),
        ('Hong Myung-bo', ['CB'], 80),
        ('Choi Soon-ho', ['ST'], 78),
        ('Hwang Bo-kwan', ['ST'], 76),
        ('Huh Jung-moo', ['CM'], 79),
        ('Kim Jae-han', ['LB'], 74),
        ('Park Hang-seo', ['CDM'], 75),
        ('Choi Kang-hee', ['CM'], 77),
        ('Kim Kwang-rae', ['RB'], 74),
        ('Byun Byung-joo', ['LM'], 75),
        ('Lee Tae-ho', ['RW'], 75),
    ]),
    ('Spain', 1990, [
        ('Andoni Zubizarreta', ['GK'], 85),
        ('Fernando Hierro', ['CB'], 83),
        ('Emilio Butragueño', ['ST'], 85),
        ('Michel', ['CM'], 84),
        ('Julio Salinas', ['ST'], 81),
        ('Martín Vázquez', ['CM'], 82),
        ('Miguel Ángel Nadal', ['CDM'], 81),
        ('Txiki Begiristain', ['LW'], 80),
        ('Jon Andoni Goikoetxea', ['CDM'], 79),
        ('José Bakero', ['CM'], 80),
        ('Andoni Goikoetxea', ['CB'], 78),
        ('Roberto Solozábal', ['CB'], 78),
        ('Míchel Salgado', ['RB'], 77),
        ('Víctor Fernández', ['CM'], 77),
        ('Manolo', ['ST'], 78),
        ('Guillermo Amor', ['CM'], 79),
    ]),
    ('Soviet Union', 1990, [
        ('Rinat Dasayev', ['GK'], 82),
        ('Alexei Mikhailichenko', ['CM'], 83),
        ('Igor Dobrovolski', ['CAM'], 83),
        ('Sergei Aleinikov', ['CM'], 81),
        ('Andrei Zygmantovich', ['CDM'], 79),
        ('Vasili Rats', ['LB'], 79),
        ('Vagiz Khidiyatullin', ['CB'], 80),
        ('Oleg Kuznetsov', ['CB'], 82),
        ('Igor Shalimov', ['CM'], 81),
        ('Sergei Rodionov', ['ST'], 79),
        ('Oleksiy Mykhaylychenko', ['CM'], 81),
        ('Armen Ambarcumjan', ['ST'], 77),
        ('Aleksandr Borodyuk', ['CM'], 78),
        ('Dzhemal Nadareyshvili', ['GK'], 76),
        ('Giorgi Lomaia', ['CB'], 76),
        ('Alexander Uvarov', ['GK'], 77),
    ]),
    ('Sweden', 1990, [
        ('Thomas Ravelli', ['GK'], 83),
        ('Tomas Brolin', ['RW'], 81),
        ('Glenn Strömberg', ['CM'], 79),
        ('Jonas Thern', ['CM'], 81),
        ('Stefan Schwarz', ['CM'], 80),
        ('Glenn Hysén', ['CB'], 80),
        ('Roger Ljung', ['LB'], 78),
        ('Martin Dahlin', ['ST'], 81),
        ('Kennet Andersson', ['ST'], 79),
        ('Joakim Nilsson', ['CB'], 78),
        ('Niclas Alexandersson', ['RM'], 77),
        ('Mikael Nilsson', ['RB'], 77),
        ('Jan Eriksson', ['CB'], 78),
        ('Johan Mjällby', ['CB'], 77),
        ('Håkan Mild', ['LM'], 78),
        ('Anders Limpar', ['LW'], 81),
    ]),
    ('UAE', 1990, [
        ('Muhsin Musabah', ['GK'], 72),
        ('Adnan Al Talyani', ['ST'], 77),
        ('Khalid Ismail Mubarak', ['CM'], 74),
        ('Ibrahim Hassan', ['CB'], 73),
        ('Fahad Khamis', ['CB'], 72),
        ('Ali Thani Jumaa', ['LB'], 72),
        ('Mohammed Ali Rashid', ['RB'], 71),
        ('Zuhair Bakheet', ['CM'], 72),
        ('Salem Al Ketbi', ['CDM'], 72),
        ('Eissa Mubarak', ['ST'], 73),
        ('Jamal Al Musabah', ['RM'], 72),
        ('Obaid Sultan', ['LM'], 71),
    ]),
    ('USA', 1990, [
        ('Tony Meola', ['GK'], 77),
        ('Paul Caligiuri', ['RM'], 77),
        ('John Harkes', ['CM'], 77),
        ('Tab Ramos', ['CAM'], 77),
        ('Peter Vermes', ['ST'], 75),
        ('Eric Wynalda', ['ST'], 77),
        ('Marcelo Balboa', ['CB'], 77),
        ('Jeff Agoos', ['LB'], 75),
        ('Brian Bliss', ['CM'], 75),
        ('Bruce Murray', ['ST'], 76),
        ('Steve Trittschuh', ['CB'], 75),
        ('Chris Henderson', ['CM'], 74),
    ]),
    ('Uruguay', 1990, [
        ('Fernando Álvez', ['GK'], 79),
        ('Enzo Francescoli', ['CAM'], 87),
        ('Daniel Fonseca', ['ST'], 82),
        ('Rubén Sosa', ['LW'], 82),
        ('Carlos Aguilera', ['LW'], 80),
        ('Hugo De León', ['CB'], 80),
        ('Ruben Paz', ['CM'], 79),
        ('Luis Marta', ['CDM'], 77),
        ('Jorge Da Silva', ['CB'], 77),
        ('Carlos Muñoz', ['RB'], 76),
        ('Jorge Barrios', ['RM'], 77),
        ('Víctor Diogo', ['ST'], 77),
        ('Miguel Polilla Da Silva', ['CM'], 78),
        ('Eduardo Acevedo', ['CM'], 76),
        ('Gustavo Veira', ['LB'], 75),
        ('Adrian Paz', ['CB'], 76),
    ]),

    # =========================================================
    # WC 1994  (24 teams; already have: Argentina, Brazil,
    #           Bulgaria, Germany, Italy, Netherlands, Romania, Sweden)
    # =========================================================
    ('Belgium', 1994, [
        ('Michel Preud\'homme', ['GK'], 83),
        ('Enzo Scifo', ['CAM'], 83),
        ('Marc Wilmots', ['CDM'], 82),
        ('Luc Nilis', ['ST'], 81),
        ('Philippe Albert', ['CB'], 82),
        ('Marc Degryse', ['RW'], 81),
        ('Franky Van Der Elst', ['CM'], 79),
        ('Eric Gerets', ['RB'], 77),
        ('Lorenzo Staelens', ['CM'], 79),
        ('Stéphane Demol', ['CB'], 77),
        ('Luis Oliveira', ['ST'], 79),
        ('Danny Boffin', ['LB'], 75),
        ('Georges Grün', ['CB'], 78),
        ('Vital Borkelmans', ['RB'], 75),
        ('Nico Claesen', ['ST'], 77),
        ('Filip De Wilde', ['GK'], 78),
    ]),
    ('Bolivia', 1994, [
        ('Carlos Trucco', ['GK'], 75),
        ('Marco Etcheverry', ['CAM'], 80),
        ('Erwin Sánchez', ['CM'], 79),
        ('Julio César Baldivieso', ['CM'], 77),
        ('Vladimir Soria', ['CDM'], 75),
        ('Marcelo Martins', ['ST'], 77),
        ('Miguel Rimba', ['CB'], 76),
        ('Gustavo Quinteros', ['CB'], 76),
        ('Lorgio Álvarez', ['LB'], 74),
        ('José Milton Melgar', ['RB'], 74),
        ('William Ramallo', ['ST'], 76),
        ('Jonny Eguino', ['RM'], 75),
    ]),
    ('Cameroon', 1994, [
        ('Jacques Songo\'o', ['GK'], 79),
        ('Roger Milla', ['ST'], 77),
        ('François Omam-Biyik', ['ST'], 79),
        ('Patrick Mboma', ['ST'], 79),
        ('Marc-Vivien Foé', ['CM'], 80),
        ('Rigobert Song', ['CB'], 79),
        ('Raymond Kalla', ['CB'], 77),
        ('Thomas Libiih', ['LB'], 76),
        ('Joseph-Antoine Bell', ['GK'], 77),
        ('Andre Kana-Biyik', ['CB'], 77),
        ('Cyrille Makanaky', ['LW'], 77),
        ('Emile Mbouh', ['CM'], 76),
    ]),
    ('Colombia', 1994, [
        ('Oscar Córdoba', ['GK'], 81),
        ('Carlos Valderrama', ['CM'], 87),
        ('Faustino Asprilla', ['RW'], 83),
        ('Freddy Rincón', ['CM'], 83),
        ('Andrés Escobar', ['CB'], 82),
        ('Adolfo Valencia', ['ST'], 82),
        ('Luis Carlos Perea', ['CB'], 81),
        ('Leonel Álvarez', ['CDM'], 79),
        ('Harold Lozano', ['LW'], 79),
        ('Óscar Tañón', ['LB'], 76),
        ('John Wilmar Pérez', ['RB'], 76),
        ('Gabriel Jaime Gómez', ['RM'], 78),
    ]),
    ('Greece', 1994, [
        ('Antonis Minou', ['GK'], 74),
        ('Nikos Machlas', ['ST'], 78),
        ('Stratos Apostolakis', ['CB'], 77),
        ('Nikos Tsiantakis', ['CM'], 76),
        ('Saravakos', ['RW'], 77),
        ('Themis Nikolaidis', ['ST'], 77),
        ('Alexis Alexandris', ['LW'], 76),
        ('Vassilis Karapialis', ['CDM'], 75),
        ('Takis Fyssas', ['LB'], 77),
        ('Giorgos Kalitzakis', ['CB'], 75),
        ('Kostas Fratzeskos', ['RB'], 74),
        ('Christos Kostis', ['CM'], 74),
    ]),
    ('Ireland', 1994, [
        ('Packie Bonner', ['GK'], 80),
        ('Paul McGrath', ['CB'], 85),
        ('Roy Keane', ['CDM'], 84),
        ('Andy Townsend', ['CM'], 81),
        ('Ray Houghton', ['CM'], 80),
        ('John Sheridan', ['CM'], 79),
        ('Steve Staunton', ['LB'], 80),
        ('Tommy Coyne', ['ST'], 77),
        ('Niall Quinn', ['ST'], 80),
        ('Tony Cascarino', ['ST'], 78),
        ('Denis Irwin', ['RB'], 82),
        ('Phil Babb', ['CB'], 80),
        ('Kevin Sheedy', ['LM'], 78),
        ('Terry Phelan', ['LB'], 79),
        ('Jason McAteer', ['RM'], 78),
        ('John Aldridge', ['ST'], 79),
    ]),
    ('Mexico', 1994, [
        ('Jorge Campos', ['GK'], 81),
        ('Luis García', ['ST'], 82),
        ('Alberto García Aspe', ['CM'], 82),
        ('Carlos Hermosillo', ['ST'], 80),
        ('Marcelino Bernal', ['CB'], 78),
        ('Claudio Suárez', ['CB'], 81),
        ('Pablo Larios', ['GK'], 77),
        ('Miguel Herrera', ['CDM'], 78),
        ('Ramón Ramírez', ['CM'], 79),
        ('Benhur Castillo', ['LB'], 76),
        ('Jorge Rodríguez', ['RB'], 76),
        ('Juan Hernández', ['LM'], 77),
        ('Zague', ['ST'], 79),
        ('Ignacio Ambriz', ['CAM'], 78),
        ('Joaquín del Olmo', ['RM'], 76),
        ('Benjamín Galindo', ['CM'], 79),
    ]),
    ('Morocco', 1994, [
        ('Khalil Azmi', ['GK'], 76),
        ('Noureddine Naybet', ['CB'], 81),
        ('Mustapha Hadji', ['CM'], 80),
        ('Rachid Azzouzi', ['CM'], 78),
        ('Abdelilah Saber', ['CB'], 77),
        ('Abdelmajid Dolmy', ['LW'], 76),
        ('Youssef Chippo', ['CDM'], 77),
        ('Rachid Daoudi', ['LB'], 75),
        ('Tahar El Khalej', ['RB'], 75),
        ('Mohammed Chaouch', ['ST'], 76),
        ('Aziz El Amrani', ['ST'], 77),
        ('Mohsine El Doua', ['RM'], 75),
    ]),
    ('Nigeria', 1994, [
        ('Peter Rufai', ['GK'], 82),
        ('Jay-Jay Okocha', ['CAM'], 84),
        ('Rashidi Yekini', ['ST'], 83),
        ('Daniel Amokachi', ['ST'], 82),
        ('Emmanuel Amuneke', ['LW'], 82),
        ('Sunday Oliseh', ['CDM'], 81),
        ('Nwankwo Kanu', ['ST'], 80),
        ('Finidi George', ['RW'], 82),
        ('Celestine Babayaro', ['LB'], 78),
        ('Uche Okechukwu', ['CB'], 79),
        ('Ben Iroha', ['CB'], 78),
        ('Nduka Ugbade', ['CM'], 77),
        ('Augustine Eguavoen', ['CDM'], 79),
        ('Mutiu Adepoju', ['CM'], 78),
        ('Samson Siasia', ['ST'], 79),
        ('Alloy Agu', ['RB'], 76),
    ]),
    ('Norway', 1994, [
        ('Erik Thorstvedt', ['GK'], 80),
        ('Jan-Åge Fjørtoft', ['ST'], 80),
        ('Jostein Flo', ['ST'], 79),
        ('Lars Bohinen', ['CM'], 81),
        ('Øyvind Leonhardsen', ['CM'], 80),
        ('Kjetil Rekdal', ['CM'], 79),
        ('Henning Berg', ['CB'], 81),
        ('Stig Inge Bjørnebye', ['LB'], 79),
        ('Gunnar Halle', ['RB'], 78),
        ('Rune Bratseth', ['CB'], 80),
        ('Roger Nilsen', ['CB'], 78),
        ('Bjørn Tore Kvarme', ['CB'], 77),
        ('Frode Grodås', ['GK'], 77),
        ('Ståle Solbakken', ['CM'], 78),
        ('Tore André Flo', ['ST'], 79),
        ('Per Frandsen', ['CM'], 78),
    ]),
    ('Russia', 1994, [
        ('Dmitri Kharine', ['GK'], 80),
        ('Oleg Salenko', ['ST'], 80),
        ('Igor Shalimov', ['CM'], 82),
        ('Andrei Kanchelskis', ['RW'], 83),
        ('Sergei Yuran', ['ST'], 82),
        ('Viktor Onopko', ['CB'], 83),
        ('Valery Karpin', ['CAM'], 81),
        ('Andrei Cherednik', ['CB'], 79),
        ('Ilya Tsymbalar', ['CM'], 80),
        ('Dmitri Galamin', ['CDM'], 78),
        ('Omari Tetradze', ['RB'], 78),
        ('Dmitri Cheryshev', ['LB'], 77),
        ('Vasili Kulkov', ['CB'], 79),
        ('Igor Dobrovolski', ['CM'], 80),
        ('Sergei Kirakov', ['LW'], 77),
        ('Aleksandr Borodyuk', ['CM'], 78),
    ]),
    ('Saudi Arabia', 1994, [
        ('Mohamed Al-Deayea', ['GK'], 83),
        ('Sami Al-Jaber', ['ST'], 80),
        ('Fuad Amin', ['CB'], 76),
        ('Yousuf Al-Thunayan', ['CM'], 77),
        ('Khaled Al-Muwallid', ['RW'], 78),
        ('Mohamed Al-Jawad', ['CDM'], 75),
        ('Hussain Sultan', ['LB'], 74),
        ('Abdulrahman Al-Ghamdi', ['CB'], 76),
        ('Hussain Sulimani', ['CM'], 76),
        ('Hani Khashoggi', ['LM'], 75),
        ('Ali Al-Thagafi', ['RB'], 74),
        ('Hamzah Idris', ['ST'], 76),
    ]),
    ('South Korea', 1994, [
        ('Hong Myung-bo', ['CB'], 83),
        ('Hwang Sun-hong', ['ST'], 81),
        ('Choi In-young', ['GK'], 78),
        ('Kim Joo-sung', ['CB'], 79),
        ('Choi Yong-soo', ['CAM'], 79),
        ('Seo Jung-won', ['CM'], 77),
        ('Lee Sang-yoon', ['LB'], 76),
        ('Shin Hong-gi', ['CDM'], 77),
        ('Kim Do-hoon', ['ST'], 78),
        ('Ko Jeong-woon', ['RB'], 75),
        ('Ko Jong-su', ['CM'], 75),
        ('Park Tae-ha', ['CB'], 76),
    ]),
    ('Spain', 1994, [
        ('Andoni Zubizarreta', ['GK'], 84),
        ('Fernando Hierro', ['CB'], 86),
        ('Miguel Ángel Nadal', ['CDM'], 82),
        ('Julio Salinas', ['ST'], 81),
        ('Txiki Begiristain', ['LW'], 80),
        ('Luis Enrique', ['CM'], 83),
        ('Guardiola', ['CM'], 84),
        ('José Bakero', ['CM'], 80),
        ('Sergi Barjuán', ['LB'], 80),
        ('Albert Ferrer', ['RB'], 80),
        ('Abelardo', ['CB'], 82),
        ('Camarasa', ['CM'], 78),
        ('Kiko', ['ST'], 79),
        ('Amavisca', ['LW'], 78),
        ('Caminero', ['CAM'], 81),
        ('Salinas Jr', ['RW'], 77),
    ]),
    ('Switzerland', 1994, [
        ('Marco Pascolo', ['GK'], 78),
        ('Stéphane Chapuisat', ['ST'], 83),
        ('Ciriaco Sforza', ['CM'], 81),
        ('Georges Bregy', ['CM'], 79),
        ('Marc Hottiger', ['RB'], 80),
        ('Alain Sutter', ['RM'], 79),
        ('Christophe Ohrel', ['LW'], 79),
        ('Yvan Quentin', ['CDM'], 77),
        ('Dominique Herr', ['CB'], 78),
        ('Johann Vogel', ['CDM'], 78),
        ('Ramon Vega', ['CB'], 78),
        ('Karl Pfeiffer', ['LB'], 75),
        ('Alain Geiger', ['CB'], 78),
        ('Stefan Lehmann', ['CM'], 76),
        ('Roy Hodgson', ['CM'], 75),
        ('Heinz Hermann', ['CM'], 77),
    ]),
    ('USA', 1994, [
        ('Tony Meola', ['GK'], 79),
        ('Alexi Lalas', ['CB'], 78),
        ('John Harkes', ['CM'], 80),
        ('Tab Ramos', ['CAM'], 79),
        ('Eric Wynalda', ['ST'], 80),
        ('Ernie Stewart', ['RW'], 79),
        ('Marcelo Balboa', ['CB'], 79),
        ('Paul Caligiuri', ['RM'], 78),
        ('Claudio Reyna', ['CM'], 80),
        ('Cobi Jones', ['LW'], 79),
        ('Brad Friedel', ['GK'], 78),
        ('Fernando Clavijo', ['CDM'], 77),
        ('Hugo Perez', ['CM'], 78),
        ('Roy Wegerle', ['ST'], 77),
        ('Mike Sorber', ['CB'], 76),
        ('Earnie Stewart', ['ST'], 79),
    ]),

    # =========================================================
    # WC 1998  (32 teams; already have: Brazil, Croatia,
    #           England, France, Netherlands)
    # =========================================================
    ('Argentina', 1998, [
        ('Carlos Roa', ['GK'], 82),
        ('Ariel Ortega', ['CAM'], 84),
        ('Gabriel Batistuta', ['ST'], 91),
        ('Juan Sebastián Verón', ['CM'], 86),
        ('Marcelo Gallardo', ['CM'], 82),
        ('Claudio López', ['RW'], 82),
        ('Roberto Ayala', ['CB'], 84),
        ('Diego Simeone', ['CDM'], 83),
        ('Nelson Vivas', ['RB'], 79),
        ('Javier Zanetti', ['RB'], 87),
        ('José Chamot', ['LB'], 80),
        ('Matías Almeyda', ['CM'], 80),
        ('Hernán Crespo', ['ST'], 84),
        ('Mauricio Pineda', ['CB'], 78),
        ('Sergio Goycochea', ['GK'], 80),
        ('Germán Burgos', ['GK'], 78),
    ]),
    ('Austria', 1998, [
        ('Michael Konsel', ['GK'], 79),
        ('Toni Polster', ['ST'], 82),
        ('Andreas Herzog', ['CAM'], 82),
        ('Peter Stoger', ['CM'], 79),
        ('Ivica Vastić', ['CAM'], 79),
        ('Anton Pfeffer', ['CB'], 77),
        ('Wolfgang Feiersinger', ['CB'], 78),
        ('Karl Heinz Schüttauer', ['LB'], 75),
        ('Markus Schopp', ['CM'], 79),
        ('Martin Amerhauser', ['RB'], 76),
        ('Thomas Linke', ['CB'], 79),
        ('Dietmar Kühbauer', ['CDM'], 79),
        ('Hans Krankl', ['ST'], 77),
        ('Hannes Reinmayr', ['LW'], 76),
        ('Werner Gregoritsch', ['ST'], 76),
        ('Gerald Willfurth', ['CM'], 75),
    ]),
    ('Belgium', 1998, [
        ('Filip De Wilde', ['GK'], 79),
        ('Marc Wilmots', ['CDM'], 82),
        ('Luis Oliveira', ['ST'], 80),
        ('Luc Nilis', ['ST'], 81),
        ('Philippe Albert', ['CB'], 82),
        ('Lorenzo Staelens', ['CM'], 79),
        ('Franky Van Der Elst', ['CM'], 78),
        ('Johan Walem', ['CM'], 78),
        ('Emile Mpenza', ['ST'], 79),
        ('Marc Degryse', ['RW'], 79),
        ('Eric Deflandre', ['RB'], 77),
        ('Reggie Blinker', ['LM'], 76),
        ('Vital Borkelmans', ['RB'], 75),
        ('Timmy Simons', ['CDM'], 76),
        ('Luc Marliers', ['CB'], 75),
        ('Branko Strupar', ['ST'], 78),
    ]),
    ('Bulgaria', 1998, [
        ('Borislav Mikhailov', ['GK'], 79),
        ('Hristo Stoichkov', ['LW'], 88),
        ('Krasimir Balakov', ['CAM'], 84),
        ('Emil Kostadinov', ['ST'], 82),
        ('Yordan Lechkov', ['CM'], 82),
        ('Trifon Ivanov', ['CB'], 80),
        ('Nasko Sirakov', ['RW'], 79),
        ('Petar Houbchev', ['CB'], 79),
        ('Zlatko Yankov', ['CDM'], 78),
        ('Bontcho Guentchev', ['LM'], 78),
        ('Ilian Iliev', ['CM'], 77),
        ('Milen Petkov', ['LB'], 76),
        ('Ivaylo Yordanov', ['CDM'], 77),
        ('Rossen Kirilov', ['RB'], 75),
        ('Daniel Borimirov', ['CM'], 78),
        ('Zdravko Zdravkov', ['GK'], 75),
    ]),
    ('Cameroon', 1998, [
        ('Jacques Songo\'o', ['GK'], 79),
        ('Patrick Mboma', ['ST'], 81),
        ('Marc-Vivien Foé', ['CM'], 82),
        ('Rigobert Song', ['CB'], 82),
        ('Samuel Eto\'o', ['ST'], 78),  # only 17
        ('Laurent Foé', ['CDM'], 79),
        ('Raymond Kalla', ['CB'], 77),
        ('Pierre Wome', ['LB'], 78),
        ('Joseph-Désiré Job', ['ST'], 79),
        ('Geremi', ['RW'], 80),
        ('Salomon Olembé', ['LM'], 77),
        ('Bill Tchato', ['RB'], 76),
        ('Alexandre Song', ['CB'], 76),
        ('Cyrille Makanaky', ['LW'], 75),
        ('Valère Billong', ['CB'], 77),
        ('Omam Biyik', ['ST'], 76),
    ]),
    ('Chile', 1998, [
        ('Nelson Tapia', ['GK'], 78),
        ('Marcelo Salas', ['ST'], 85),
        ('Iván Zamorano', ['ST'], 86),
        ('Marcelo Espina', ['CM'], 79),
        ('Clarence Acuña', ['CM'], 79),
        ('Nelson Parraguez', ['CB'], 78),
        ('Óscar Romero', ['CDM'], 77),
        ('Miguel Ramírez', ['LB'], 76),
        ('Rodrigo Barrera', ['RB'], 76),
        ('Fabián Estay', ['RM'], 77),
        ('Pedro Reyes', ['CB'], 76),
        ('Rodrigo Goldberg', ['LW'], 77),
        ('Luis Musrri', ['CM'], 75),
        ('Cristián Castañeda', ['RB'], 75),
        ('Gonzalo Fierro', ['CM'], 76),
        ('Sebastián González', ['ST'], 77),
    ]),
    ('Colombia', 1998, [
        ('Oscar Córdoba', ['GK'], 82),
        ('Carlos Valderrama', ['CM'], 86),
        ('Faustino Asprilla', ['RW'], 83),
        ('Freddy Rincón', ['CM'], 82),
        ('Hamilton Ricard', ['ST'], 80),
        ('Ivan Ramiro Cordoba', ['CB'], 82),
        ('Andrés Palacios', ['LB'], 77),
        ('Harold Lozano', ['LW'], 79),
        ('Rafael Dudamel', ['GK'], 79),
        ('Víctor Aristizábal', ['ST'], 80),
        ('Jairo Castillo', ['ST'], 78),
        ('Adolfo Valencia', ['ST'], 79),
        ('Gerardo Bedoya', ['CDM'], 79),
        ('Luis Carlos Perea', ['CB'], 79),
        ('Mauricio Serna', ['RM'], 77),
        ('Antony de Ávila', ['LM'], 77),
    ]),
    ('Denmark', 1998, [
        ('Peter Schmeichel', ['GK'], 90),
        ('Michael Laudrup', ['CAM'], 88),
        ('Brian Laudrup', ['RW'], 87),
        ('Jon Dahl Tomasson', ['ST'], 83),
        ('Peter Møller', ['ST'], 81),
        ('Thomas Helveg', ['RB'], 81),
        ('Marc Rieper', ['CB'], 81),
        ('Per Frandsen', ['CM'], 79),
        ('Flemming Póvlsen', ['LW'], 79),
        ('Jes Hogh', ['CB'], 79),
        ('Allan Nielsen', ['CM'], 80),
        ('Søren Colding', ['LB'], 76),
        ('Mikkel Beck', ['ST'], 78),
        ('Morten Wieghorst', ['CM'], 79),
        ('Niclas Jensen', ['LB'], 78),
        ('Claus Thomsen', ['CDM'], 77),
    ]),
    ('Germany', 1998, [
        ('Oliver Kahn', ['GK'], 90),
        ('Jürgen Klinsmann', ['ST'], 87),
        ('Lothar Matthäus', ['CM'], 86),
        ('Andreas Möller', ['CAM'], 86),
        ('Oliver Bierhoff', ['ST'], 84),
        ('Stefan Effenberg', ['CM'], 86),
        ('Matthias Sammer', ['CB'], 87),
        ('Christian Ziege', ['LB'], 83),
        ('Thomas Helmer', ['CB'], 83),
        ('Markus Babbel', ['RB'], 82),
        ('Karl-Heinz Riedle', ['ST'], 81),
        ('Mehmet Scholl', ['CAM'], 83),
        ('Dieter Eilts', ['CDM'], 79),
        ('Carsten Jancker', ['ST'], 79),
        ('Fredi Bobic', ['ST'], 79),
        ('Michael Tarnat', ['LB'], 79),
    ]),
    ('Iran', 1998, [
        ('Ahmad Reza Abedzadeh', ['GK'], 78),
        ('Ali Daei', ['ST'], 81),
        ('Karim Bagheri', ['CAM'], 80),
        ('Mehdi Mahdavikia', ['RW'], 80),
        ('Khodadad Azizi', ['LW'], 79),
        ('Ali Parvin', ['CDM'], 77),
        ('Rahman Rezaei', ['CB'], 78),
        ('Nader Mohammadkhani', ['CB'], 77),
        ('Sirous Dinmohammadi', ['LB'], 76),
        ('Vahid Hashemian', ['ST'], 78),
        ('Sirus Dinmohammadi', ['CM'], 75),
        ('Mohammad Khakpour', ['RB'], 75),
        ('Rasoul Khorshidi', ['LM'], 76),
        ('Behnam Ghasempour', ['CB'], 75),
        ('Ali Mansourian', ['CM'], 76),
        ('Hamid Reza Estili', ['CM'], 77),
    ]),
    ('Italy', 1998, [
        ('Gianluigi Buffon', ['GK'], 84),
        ('Roberto Baggio', ['CAM'], 90),
        ('Alessandro Del Piero', ['ST'], 89),
        ('Christian Vieri', ['ST'], 87),
        ('Filippo Inzaghi', ['ST'], 86),
        ('Demetrio Albertini', ['CM'], 83),
        ('Paolo Maldini', ['LB'], 92),
        ('Fabio Cannavaro', ['CB'], 85),
        ('Alessandro Costacurta', ['CB'], 84),
        ('Ciro Ferrara', ['CB'], 82),
        ('Gianluca Pagliuca', ['GK'], 84),
        ('Luigi Di Biagio', ['CM'], 82),
        ('Roberto Di Matteo', ['CDM'], 82),
        ('Angelo Di Livio', ['RM'], 80),
        ('Francesco Totti', ['CAM'], 83),
        ('Nicola Berti', ['CM'], 80),
    ]),
    ('Jamaica', 1998, [
        ('Warren Barrett', ['GK'], 74),
        ('Deon Burton', ['ST'], 76),
        ('Marcus Gayle', ['ST'], 76),
        ('Theodore Whitmore', ['CM'], 77),
        ('Ricardo Gardner', ['LB'], 78),
        ('Paul Hall', ['RM'], 76),
        ('Fitzroy Simpson', ['CDM'], 75),
        ('Ian Goodison', ['CB'], 75),
        ('Christopher Dawes', ['CB'], 74),
        ('Robbie Earle', ['CM'], 77),
        ('Frank Sinclair', ['CB'], 77),
        ('Steve Malcolm', ['RB'], 74),
    ]),
    ('Japan', 1998, [
        ('Yoshikatsu Kawaguchi', ['GK'], 80),
        ('Hidetoshi Nakata', ['CAM'], 85),
        ('Masashi Nakayama', ['ST'], 80),
        ('Shunsuke Nakamura', ['CAM'], 82),
        ('Shinji Ono', ['CM'], 78),
        ('Kazuyoshi Miura', ['ST'], 79),
        ('Akira Nishino', ['CB'], 76),
        ('Norio Omura', ['CB'], 76),
        ('Koji Nakata', ['CB'], 79),
        ('Shoji Jo', ['LB'], 75),
        ('Naoki Matsuda', ['CB'], 78),
        ('Teruyoshi Ito', ['RM'], 77),
        ('Masami Ihara', ['CB'], 77),
        ('Motohiro Yamaguchi', ['CDM'], 76),
        ('Hiroshi Nanami', ['CM'], 78),
        ('Eisuke Nakanishi', ['GK'], 74),
    ]),
    ('Mexico', 1998, [
        ('Jorge Campos', ['GK'], 82),
        ('Luis García', ['ST'], 83),
        ('Cuauhtémoc Blanco', ['CAM'], 84),
        ('Claudio Suárez', ['CB'], 83),
        ('Alberto García Aspe', ['CM'], 82),
        ('Rafael Márquez', ['CB'], 81),
        ('Ricardo Peláez', ['CM'], 79),
        ('Ramón Ramírez', ['CM'], 79),
        ('Salvador Carmona', ['LB'], 78),
        ('Germán Villa', ['CDM'], 77),
        ('Jorge Campos Jr', ['GK'], 79),
        ('Jesús Arellano', ['RW'], 78),
        ('Mario Rodríguez', ['RB'], 76),
        ('Sergio García', ['ST'], 77),
        ('Carlos Hermosillo', ['ST'], 79),
        ('Benjamín Galindo', ['CM'], 77),
    ]),
    ('Morocco', 1998, [
        ('Khalil Azmi', ['GK'], 77),
        ('Noureddine Naybet', ['CB'], 82),
        ('Mustapha Hadji', ['CM'], 81),
        ('Youssef Chippo', ['CM'], 80),
        ('Rachid Azzouzi', ['CM'], 78),
        ('Abdelilah Saber', ['CB'], 77),
        ('Tahar El Khalej', ['RB'], 77),
        ('Rachid Daoudi', ['LB'], 76),
        ('Driss Benhbarka', ['ST'], 77),
        ('Aziz Bouderbala', ['RW'], 75),
        ('Mohammed Timoumi', ['CM'], 75),
        ('Bassir', ['ST'], 78),
        ('Khairi Baha', ['CB'], 75),
        ('Said Chiba', ['CDM'], 75),
        ('Amine Ouchan', ['LW'], 74),
        ('Salaheddine Bassir', ['ST'], 78),
    ]),
    ('Nigeria', 1998, [
        ('Peter Rufai', ['GK'], 82),
        ('Jay-Jay Okocha', ['CAM'], 86),
        ('Nwankwo Kanu', ['ST'], 83),
        ('Finidi George', ['RW'], 83),
        ('Celestine Babayaro', ['LB'], 81),
        ('Sunday Oliseh', ['CDM'], 82),
        ('Daniel Amokachi', ['ST'], 82),
        ('Garba Lawal', ['CM'], 79),
        ('Taribo West', ['CB'], 82),
        ('Uche Okechukwu', ['CB'], 80),
        ('Victor Ikpeba', ['LW'], 80),
        ('Mutiu Adepoju', ['CM'], 79),
        ('Emmanuel Amuneke', ['LW'], 80),
        ('Augustine Eguavoen', ['CDM'], 79),
        ('Isaac Okoronkwo', ['CB'], 78),
        ('Dosu Joseph', ['GK'], 77),
    ]),
    ('Norway', 1998, [
        ('Frode Grodås', ['GK'], 79),
        ('Ole Gunnar Solskjær', ['ST'], 84),
        ('Tore André Flo', ['ST'], 83),
        ('Kjetil Rekdal', ['CM'], 80),
        ('Øyvind Leonhardsen', ['CM'], 81),
        ('Lars Bohinen', ['CM'], 80),
        ('Henning Berg', ['CB'], 82),
        ('Vegard Heggem', ['RB'], 79),
        ('Stig Inge Bjørnebye', ['LB'], 79),
        ('Ronny Johnsen', ['CB'], 82),
        ('Håvard Flo', ['ST'], 79),
        ('Roar Strand', ['CM'], 78),
        ('Erik Mykland', ['LM'], 79),
        ('Jostein Flo', ['ST'], 78),
        ('Dan Eggen', ['CB'], 77),
        ('Claus Lundekvam', ['CB'], 78),
    ]),
    ('Paraguay', 1998, [
        ('José Luis Chilavert', ['GK'], 86),
        ('Roque Santa Cruz', ['ST'], 82),
        ('Carlos Gamarra', ['CB'], 83),
        ('Francisco Arce', ['LB'], 80),
        ('Celso Ayala', ['CB'], 80),
        ('Robert Acuña', ['CM'], 79),
        ('Jorge Campos (PAR)', ['CDM'], 77),
        ('Miguel Ángel Benítez', ['RW'], 78),
        ('Dionisio Samaniego', ['CM'], 77),
        ('Juan Manuel Escobar', ['RB'], 77),
        ('Óscar Ruggeri (PAR)', ['CB'], 77),
        ('Nelson Cuevas', ['LW'], 79),
        ('Julio César Manzur', ['CM'], 76),
        ('Blas Santana', ['ST'], 77),
        ('Gustavo Neffa', ['CM'], 76),
        ('Arce José', ['CM'], 75),
    ]),
    ('Romania', 1998, [
        ('Bogdan Stelea', ['GK'], 79),
        ('Gheorghe Hagi', ['CAM'], 88),
        ('Adrian Ilie', ['LW'], 82),
        ('Viorel Moldovan', ['ST'], 81),
        ('Florin Răducioiu', ['ST'], 81),
        ('Gheorghe Popescu', ['CDM'], 84),
        ('Dan Petrescu', ['RB'], 82),
        ('Mircea Lucescu Jr', ['RM'], 78),
        ('Miodrag Belodedici', ['CB'], 80),
        ('Cosmin Contra', ['RB'], 78),
        ('Ioan Sabău', ['CM'], 77),
        ('Liviu Ciobotariu', ['CM'], 79),
        ('Constantin Gâlcă', ['CM'], 79),
        ('Dorinel Munteanu', ['CM'], 80),
        ('Marius Lăcătuș', ['RW'], 78),
        ('Anton Doboș', ['GK'], 75),
    ]),
    ('Saudi Arabia', 1998, [
        ('Mohamed Al-Deayea', ['GK'], 83),
        ('Sami Al-Jaber', ['ST'], 81),
        ('Yousuf Al-Thunayan', ['CM'], 78),
        ('Fuad Amin', ['CB'], 76),
        ('Khaled Al-Muwallid', ['RW'], 79),
        ('Fahad Al-Ghesheyan', ['ST'], 77),
        ('Abdullah Zubromawi', ['CB'], 77),
        ('Mohammed Al-Jawad', ['CDM'], 76),
        ('Hussain Sultan', ['LB'], 75),
        ('Ismail Al-Sherif', ['RB'], 74),
        ('Ahmed Bahja', ['CM'], 76),
        ('Khamees Al-Owairan', ['RW'], 77),
    ]),
    ('Scotland', 1998, [
        ('Jim Leighton', ['GK'], 79),
        ('Craig Burley', ['CM'], 80),
        ('Kevin Gallacher', ['ST'], 79),
        ('John Collins', ['CM'], 81),
        ('Gordon Durie', ['ST'], 78),
        ('Christian Dailly', ['CB'], 78),
        ('Tom Boyd', ['LB'], 78),
        ('Colin Hendry', ['CB'], 81),
        ('Gary McAllister', ['CM'], 82),
        ('Colin Calderwood', ['CB'], 79),
        ('Scott Booth', ['ST'], 78),
        ('Darren Jackson', ['LW'], 77),
        ('Scot Gemmill', ['CM'], 78),
        ('David Weir', ['CB'], 80),
        ('Ally McCoist', ['ST'], 79),
        ('Matt Elliott', ['CB'], 78),
    ]),
    ('South Africa', 1998, [
        ('Hans Vonk', ['GK'], 76),
        ('Benni McCarthy', ['ST'], 81),
        ('Shaun Bartlett', ['ST'], 79),
        ('Mark Fish', ['CB'], 80),
        ('Lucas Radebe', ['CB'], 82),
        ('Quinton Fortune', ['LW'], 80),
        ('Sibusiso Zuma', ['RW'], 78),
        ('Phil Masinga', ['ST'], 78),
        ('John Moshoeu', ['CM'], 79),
        ('Sizwe Motaung', ['CM'], 77),
        ('Pierre Issa', ['CB'], 78),
        ('Theophilus Khumalo', ['CDM'], 77),
        ('Doctor Khumalo', ['CAM'], 79),
        ('Neil Tovey', ['CB'], 76),
        ('Delron Buckley', ['LM'], 76),
        ('Brian Baloyi', ['GK'], 74),
    ]),
    ('South Korea', 1998, [
        ('Kim Byung-ji', ['GK'], 79),
        ('Hong Myung-bo', ['CB'], 84),
        ('Hwang Sun-hong', ['ST'], 82),
        ('Choi Yong-soo', ['CAM'], 81),
        ('Ha Seok-ju', ['CM'], 79),
        ('Kim Do-hoon', ['ST'], 80),
        ('Ko Jeong-woon', ['RB'], 77),
        ('Lee Lim-saeng', ['LB'], 77),
        ('Yoon Jong-hwan', ['CM'], 79),
        ('Cha Bum-kun Jr', ['CM'], 78),
        ('Seol Ki-hyeon', ['RW'], 79),
        ('Choi Jin-cheul', ['CB'], 79),
        ('Seo Jung-won', ['CM'], 77),
        ('Ko Jong-su', ['CDM'], 77),
        ('Lee Do-hoon', ['ST'], 77),
        ('Kim Tae-young', ['CB'], 76),
    ]),
    ('Spain', 1998, [
        ('Andoni Zubizarreta', ['GK'], 83),
        ('Fernando Hierro', ['CB'], 87),
        ('Raúl', ['ST'], 87),
        ('Fernando Morientes', ['ST'], 83),
        ('Luis Enrique', ['CM'], 83),
        ('Pep Guardiola', ['CM'], 83),
        ('Alfonso Pérez', ['ST'], 81),
        ('Sergi Barjuán', ['LB'], 80),
        ('Albert Ferrer', ['RB'], 80),
        ('Miguel Ángel Nadal', ['CDM'], 82),
        ('Abelardo', ['CB'], 82),
        ('Víctor Fernández', ['CM'], 78),
        ('Kiko', ['ST'], 80),
        ('Caminero', ['CAM'], 80),
        ('Juninho (ESP)', ['CM'], 78),
        ('Santiago Cañizares', ['GK'], 82),
    ]),
    ('Tunisia', 1998, [
        ('Chokri El Ouaer', ['GK'], 77),
        ('Adel Sellimi', ['RW'], 79),
        ('Riadh Bouazizi', ['CM'], 78),
        ('Skander Souayah', ['ST'], 77),
        ('Wissem Bekri', ['CB'], 76),
        ('Hatem Trabelsi', ['RB'], 80),
        ('Tarek Thabet', ['CDM'], 76),
        ('Mourad Melayah', ['CM'], 77),
        ('Ferid Chouchane', ['LB'], 75),
        ('Imed Ben Younes', ['LW'], 76),
        ('Ali Boumnijel', ['GK'], 76),
        ('Sami Trabelsi', ['CB'], 76),
    ]),
    ('USA', 1998, [
        ('Kasey Keller', ['GK'], 80),
        ('Claudio Reyna', ['CM'], 81),
        ('Brian McBride', ['ST'], 80),
        ('Eric Wynalda', ['ST'], 80),
        ('Cobi Jones', ['LW'], 79),
        ('Tab Ramos', ['CAM'], 78),
        ('Alexi Lalas', ['CB'], 78),
        ('John Harkes', ['CM'], 79),
        ('Marcelo Balboa', ['CB'], 79),
        ('Brad Friedel', ['GK'], 80),
        ('Jeff Agoos', ['LB'], 77),
        ('Eddie Pope', ['CB'], 79),
        ('Roy Wegerle', ['ST'], 77),
        ('David Regis', ['RB'], 76),
        ('Earnie Stewart', ['ST'], 79),
        ('Mike Burns', ['RB'], 76),
    ]),
    ('Yugoslavia', 1998, [
        ('Ivica Kralj', ['GK'], 79),
        ('Predrag Mijatović', ['ST'], 85),
        ('Dragan Stojković', ['CAM'], 87),
        ('Siniša Mihajlović', ['LB'], 85),
        ('Dejan Savičević', ['CAM'], 86),
        ('Vladislav Jugović', ['CM'], 82),
        ('Slobodan Komljenović', ['CM'], 79),
        ('Zoran Mirković', ['RB'], 80),
        ('Ljubinko Drulović', ['CB'], 79),
        ('Gordan Petric', ['CB'], 80),
        ('Vladimir Beara', ['GK'], 76),
        ('Nikola Lazetić', ['CB'], 78),
        ('Slaviša Jokanović', ['CDM'], 81),
        ('Milan Milovanović', ['ST'], 77),
        ('Branko Brnović', ['LM'], 77),
        ('Darko Kovačević', ['ST'], 82),
    ]),

    # =========================================================
    # WC 2002  (32 teams; already have: Argentina, Brazil,
    #           England, Germany, Turkey)
    # =========================================================
    ('Belgium', 2002, [
        ('Filip De Wilde', ['GK'], 79),
        ('Marc Wilmots', ['CDM'], 82),
        ('Emile Mpenza', ['ST'], 80),
        ('Johan Walem', ['CM'], 79),
        ('Philippe Albert', ['CB'], 80),
        ('Daniel van Buyten', ['CB'], 80),
        ('Timmy Simons', ['CDM'], 78),
        ('Gert Verheyen', ['RM'], 77),
        ('Geert De Vlieger', ['GK'], 77),
        ('Eric Deflandre', ['RB'], 77),
        ('Glen De Boeck', ['CB'], 76),
        ('Yves Vanderhaeghe', ['CM'], 77),
        ('Sven Vermant', ['CM'], 77),
        ('Branko Strupar', ['ST'], 78),
        ('Bart Goor', ['CM'], 78),
        ('Jacky Peeters', ['LB'], 75),
    ]),
    ('Cameroon', 2002, [
        ('Alioum Boukar', ['GK'], 76),
        ('Samuel Eto\'o', ['ST'], 82),
        ('Marc-Vivien Foé', ['CM'], 83),
        ('Patrick Mboma', ['ST'], 82),
        ('Rigobert Song', ['CB'], 82),
        ('Geremi', ['RW'], 82),
        ('Pierre Wome', ['LB'], 79),
        ('Salomon Olembé', ['LM'], 78),
        ('Lauren', ['RB'], 82),
        ('Alphonse Tchami', ['CB'], 77),
        ('Joseph-Désiré Job', ['ST'], 79),
        ('Serge Branco', ['CB'], 77),
        ('Bill Tchato', ['RB'], 76),
        ('Valère Billong', ['CB'], 76),
        ('Jean-Guy Wallemme', ['CDM'], 77),
        ('Idriss Carlos Kameni', ['GK'], 75),
    ]),
    ('China', 2002, [
        ('Jiang Jin', ['GK'], 74),
        ('Fan Zhiyi', ['CB'], 79),
        ('Hao Haidong', ['ST'], 78),
        ('Li Xiaopeng', ['CM'], 76),
        ('Sun Jihai', ['RB'], 77),
        ('Zheng Zhi', ['CM'], 77),
        ('Yang Chen', ['CDM'], 74),
        ('Li Weifeng', ['CB'], 76),
        ('Ou Chuliang', ['LW'], 74),
        ('Wu Chengying', ['ST'], 73),
        ('Qi Hong', ['LB'], 73),
        ('Ma Lin', ['RM'], 73),
    ]),
    ('Costa Rica', 2002, [
        ('Álvaro Mesén', ['GK'], 77),
        ('Ronald Gómez', ['ST'], 78),
        ('Paulo Wanchope', ['ST'], 81),
        ('Hernán Medford', ['RW'], 78),
        ('Mauricio Solís', ['CM'], 78),
        ('Harold Wallace', ['CB'], 76),
        ('Gilberto Martínez', ['CDM'], 76),
        ('Mauricio Wright', ['CB'], 77),
        ('Luis Marín', ['LB'], 76),
        ('Rónald Gómez', ['LM'], 77),
        ('Minor López', ['RB'], 75),
        ('Jafet Soto', ['CM'], 75),
        ('Óscar Rojas', ['CB'], 75),
        ('Andres Fernandez', ['GK'], 74),
        ('Douglas Sequeira', ['CDM'], 74),
        ('Elvis Brenes', ['RM'], 74),
    ]),
    ('Croatia', 2002, [
        ('Stipe Pletikosa', ['GK'], 80),
        ('Ivica Olić', ['ST'], 81),
        ('Niko Kovač', ['CM'], 81),
        ('Robert Kovač', ['CB'], 80),
        ('Darijo Srna', ['RB'], 80),
        ('Dario Šimić', ['CB'], 82),
        ('Igor Tudor', ['CB'], 81),
        ('Miroslav Ćiro Blažević', ['CM'], 77),
        ('Mladen Petrić', ['ST'], 78),
        ('Marko Babić', ['CM'], 78),
        ('Dado Pršo', ['ST'], 79),
        ('Tomislav Marić', ['LB'], 76),
        ('Igor Pamić', ['RB'], 76),
        ('Stjepan Tomas', ['CDM'], 78),
        ('Luka Modrić', ['CM'], 77),  # 16 years old!
        ('Ivan Klasnić', ['ST'], 80),
    ]),
    ('Denmark', 2002, [
        ('Thomas Sørensen', ['GK'], 80),
        ('Jon Dahl Tomasson', ['ST'], 84),
        ('Ebbe Sand', ['ST'], 82),
        ('Thomas Helveg', ['RB'], 81),
        ('Stig Tøfting', ['CDM'], 80),
        ('Niclas Jensen', ['LB'], 79),
        ('Martin Jørgensen', ['RM'], 80),
        ('Dennis Rommedahl', ['LW'], 81),
        ('Marc Rieper', ['CB'], 79),
        ('Søren Colding', ['LB'], 75),
        ('Claus Jensen', ['CM'], 79),
        ('Per Frandsen', ['CM'], 79),
        ('Morten Wieghorst', ['CM'], 77),
        ('René Henriksen', ['CB'], 78),
        ('John Dahl Tomasson Jr', ['CM'], 76),
        ('Peter Kjær', ['GK'], 76),
    ]),
    ('Ecuador', 2002, [
        ('Cristian Mora', ['GK'], 75),
        ('Agustín Delgado', ['ST'], 80),
        ('Edison Méndez', ['CM'], 79),
        ('Iván Kaviedes', ['ST'], 78),
        ('Ulises de la Cruz', ['RB'], 80),
        ('Iván Hurtado', ['CB'], 81),
        ('Patricio Urrutia', ['CM'], 77),
        ('Neicer Reasco', ['LB'], 76),
        ('Luis Capurro', ['CB'], 76),
        ('Franklin Salas', ['LM'], 76),
        ('Raúl Guerrón', ['RM'], 75),
        ('Giovanni Ibarra', ['CDM'], 75),
    ]),
    ('France', 2002, [
        ('Fabien Barthez', ['GK'], 88),
        ('Zinedine Zidane', ['CAM'], 92),
        ('Thierry Henry', ['ST'], 91),
        ('Patrick Vieira', ['CM'], 91),
        ('Robert Pirès', ['LW'], 88),
        ('Lilian Thuram', ['RB'], 88),
        ('Marcel Desailly', ['CB'], 87),
        ('Laurent Blanc', ['CB'], 86),
        ('Emmanuel Petit', ['CDM'], 84),
        ('Sylvain Wiltord', ['LW'], 84),
        ('David Trezeguet', ['ST'], 87),
        ('Bixente Lizarazu', ['LB'], 85),
        ('Christophe Dugarry', ['ST'], 82),
        ('Alain Boghossian', ['CM'], 79),
        ('Mikael Silvestre', ['CB'], 82),
        ('Claude Makélélé', ['CDM'], 88),
    ]),
    ('Ireland', 2002, [
        ('Shay Given', ['GK'], 83),
        ('Roy Keane', ['CDM'], 90),
        ('Damien Duff', ['LW'], 84),
        ('Niall Quinn', ['ST'], 80),
        ('Robbie Keane', ['ST'], 83),
        ('Steve Staunton', ['LB'], 79),
        ('Richard Dunne', ['CB'], 81),
        ('Gary Breen', ['CB'], 79),
        ('Gary Kelly', ['RB'], 79),
        ('Ian Harte', ['LB'], 80),
        ('Matt Holland', ['CM'], 79),
        ('Mark Kinsella', ['CM'], 79),
        ('Clinton Morrison', ['ST'], 77),
        ('Kevin Kilbane', ['LM'], 79),
        ('Jason McAteer', ['RM'], 78),
        ('Colin Healy', ['CM'], 77),
    ]),
    ('Italy', 2002, [
        ('Gianluigi Buffon', ['GK'], 88),
        ('Alessandro Del Piero', ['ST'], 89),
        ('Francesco Totti', ['CAM'], 89),
        ('Christian Vieri', ['ST'], 88),
        ('Filippo Inzaghi', ['ST'], 86),
        ('Paolo Maldini', ['LB'], 91),
        ('Fabio Cannavaro', ['CB'], 87),
        ('Alessandro Nesta', ['CB'], 89),
        ('Marco Materazzi', ['CB'], 83),
        ('Alessandro Costacurta', ['CB'], 83),
        ('Gennaro Gattuso', ['CDM'], 85),
        ('Gianluca Zambrotta', ['RB'], 84),
        ('Demetrio Albertini', ['CM'], 82),
        ('Damiano Tommasi', ['CM'], 82),
        ('Vincenzo Montella', ['ST'], 83),
        ('Stefano Fiore', ['LM'], 80),
    ]),
    ('Japan', 2002, [
        ('Seigo Narazaki', ['GK'], 80),
        ('Hidetoshi Nakata', ['CAM'], 86),
        ('Junichi Inamoto', ['CM'], 82),
        ('Shinji Ono', ['CM'], 80),
        ('Shunsuke Nakamura', ['CAM'], 84),
        ('Koji Nakata', ['CB'], 80),
        ('Naoki Matsuda', ['CB'], 80),
        ('Makoto Tanaka', ['LB'], 77),
        ('Santos (JPN)', ['CB'], 79),
        ('Atsushi Yanagisawa', ['ST'], 79),
        ('Yoshikatsu Kawaguchi', ['GK'], 81),
        ('Masashi Nakayama', ['ST'], 80),
        ('Alex (JPN)', ['LW'], 78),
        ('Yasuhito Endo', ['CM'], 78),
        ('Takayuki Suzuki', ['ST'], 79),
        ('Tsuneyasu Miyamoto', ['CB'], 79),
    ]),
    ('Mexico', 2002, [
        ('Óscar Pérez', ['GK'], 81),
        ('Cuauhtémoc Blanco', ['CAM'], 84),
        ('Jared Borgetti', ['ST'], 83),
        ('Claudio Suárez', ['CB'], 83),
        ('Rafael Márquez', ['CB'], 83),
        ('Gerardo Torrado', ['CDM'], 80),
        ('Pavel Pardo', ['CM'], 80),
        ('Ramón Morales', ['LM'], 78),
        ('Alberto García Aspe', ['CM'], 80),
        ('Jorge Campos', ['GK'], 79),
        ('Oswaldo Sánchez', ['GK'], 79),
        ('Fernando Quirarte Jr', ['CB'], 77),
        ('Sigifredo Mercado', ['CM'], 77),
        ('José Luis Real', ['RB'], 76),
        ('Braulio Luna', ['LB'], 76),
        ('Christian Torres', ['RM'], 77),
    ]),
    ('Nigeria', 2002, [
        ('Ike Shorunmu', ['GK'], 78),
        ('Jay-Jay Okocha', ['CAM'], 86),
        ('Nwankwo Kanu', ['ST'], 83),
        ('Celestine Babayaro', ['LB'], 82),
        ('Finidi George', ['RW'], 81),
        ('Sunday Oliseh', ['CDM'], 82),
        ('Garba Lawal', ['CM'], 80),
        ('Taribo West', ['CB'], 81),
        ('Augustine Eguavoen', ['CDM'], 78),
        ('John Obi Mikel', ['CM'], 76),  # very young
        ('Efan Ekoku', ['ST'], 78),
        ('Emeka Ezeugo', ['CB'], 76),
        ('Chidi Nwosu', ['LB'], 76),
        ('Tijani Babangida', ['LW'], 79),
        ('Victor Agali', ['ST'], 78),
        ('Obafemi Martins', ['ST'], 77),
    ]),
    ('Paraguay', 2002, [
        ('José Luis Chilavert', ['GK'], 85),
        ('Roque Santa Cruz', ['ST'], 84),
        ('Carlos Gamarra', ['CB'], 83),
        ('Francisco Arce', ['LB'], 80),
        ('Celso Ayala', ['CB'], 80),
        ('Robert Acuña', ['CM'], 80),
        ('Nelson Cuevas', ['LW'], 80),
        ('Jorge Campos (PAR)', ['CDM'], 77),
        ('Diego Gavilán', ['CM'], 78),
        ('Óscar Cardozo', ['ST'], 79),
        ('Julio César Manzur', ['CM'], 77),
        ('Justo Villar', ['GK'], 78),
        ('Víctor Cáceres', ['CB'], 77),
        ('Raúl Bobadilla', ['ST'], 77),
        ('Carlos Paredes', ['CDM'], 78),
        ('Roberto Acuña', ['RM'], 77),
    ]),
    ('Poland', 2002, [
        ('Jerzy Dudek', ['GK'], 84),
        ('Emanuel Olisadebe', ['ST'], 82),
        ('Marcin Żewłakow', ['ST'], 81),
        ('Jacek Bąk', ['CB'], 79),
        ('Tomasz Kłos', ['CB'], 79),
        ('Radosław Kałużny', ['CM'], 79),
        ('Maciej Żurawski', ['ST'], 80),
        ('Arkadiusz Głowacki', ['CB'], 77),
        ('Tomasz Hajto', ['CDM'], 79),
        ('Piotr Świerczewski', ['CM'], 79),
        ('Michał Żewłakow', ['RB'], 78),
        ('Marek Koźmiński', ['LB'], 77),
        ('Bartosz Karwan', ['LW'], 77),
        ('Paweł Kryszałowicz', ['ST'], 78),
        ('Mariusz Jop', ['CB'], 76),
        ('Jacek Krzynówek', ['RM'], 79),
    ]),
    ('Portugal', 2002, [
        ('Vítor Baía', ['GK'], 84),
        ('Luís Figo', ['RW'], 93),
        ('Rui Costa', ['CAM'], 90),
        ('João Pinto', ['ST'], 83),
        ('Pauleta', ['ST'], 85),
        ('Fernando Couto', ['CB'], 85),
        ('Jorge Costa', ['CB'], 82),
        ('Abel Xavier', ['RB'], 80),
        ('João Vieira Pinto', ['LM'], 80),
        ('Sérgio Conceição', ['RM'], 82),
        ('Simão Sabrosa', ['LW'], 82),
        ('Pedro Pauleta', ['ST'], 84),
        ('Nuno Valente', ['LB'], 81),
        ('Ricardo Carvalho', ['CB'], 83),
        ('Manuel Rui Costa', ['CAM'], 88),
        ('Paulo Bento', ['CDM'], 79),
    ]),
    ('Russia', 2002, [
        ('Sergei Ovchinnikov', ['GK'], 80),
        ('Andrei Kanchelskis', ['RW'], 82),
        ('Valery Karpin', ['CAM'], 81),
        ('Viktor Onopko', ['CB'], 82),
        ('Sergei Ignashevich', ['CB'], 81),
        ('Yuri Nikiforov', ['CB'], 80),
        ('Alexei Smertin', ['CM'], 80),
        ('Dmitri Loskov', ['CM'], 79),
        ('Ruslan Nigmatullin', ['GK'], 79),
        ('Dmitry Bulychev', ['ST'], 77),
        ('Yegor Titov', ['CM'], 80),
        ('Alexander Mostovoi', ['CM'], 81),
        ('Rolan Gusev', ['RM'], 78),
        ('Andrei Solomatin', ['RB'], 77),
        ('Dmitri Bulykin', ['ST'], 78),
        ('Marat Izmailov', ['LW'], 77),
    ]),
    ('Saudi Arabia', 2002, [
        ('Mohamed Al-Deayea', ['GK'], 83),
        ('Sami Al-Jaber', ['ST'], 82),
        ('Yousuf Al-Thunayan', ['CM'], 78),
        ('Fuad Amin', ['CB'], 75),
        ('Khaled Al-Muwallid', ['RW'], 79),
        ('Abdullah Zubromawi', ['CB'], 77),
        ('Mohammed Al-Jawad', ['CDM'], 76),
        ('Fahad Al-Ghesheyan', ['ST'], 76),
        ('Hussain Sultan', ['LB'], 74),
        ('Nawaf Al-Temyat', ['CM'], 78),
        ('Ahmed Al-Dokhi', ['CB'], 76),
        ('Ismail Al-Sherif', ['RB'], 74),
    ]),
    ('Senegal', 2002, [
        ('Tony Sylva', ['GK'], 79),
        ('El Hadji Diouf', ['RW'], 83),
        ('Khalilou Fadiga', ['CM'], 81),
        ('Papa Bouba Diop', ['CM'], 81),
        ('Henri Camara', ['ST'], 80),
        ('Salif Diao', ['CDM'], 80),
        ('Pape Thiaw', ['CB'], 78),
        ('Ferdinand Coly', ['LB'], 79),
        ('Aliou Cissé', ['CDM'], 78),
        ('Lamine Diatta', ['CB'], 77),
        ('Amdy Faye', ['CM'], 78),
        ('Ibrahima Gueye', ['RB'], 76),
        ('Habib Beye', ['RB'], 77),
        ('Mamadou Diallo', ['ST'], 77),
        ('Cheikhou Diop', ['CB'], 76),
        ('Pape Sarr', ['LM'], 75),
    ]),
    ('Slovenia', 2002, [
        ('Borut Majer', ['GK'], 75),
        ('Zlatko Zahovič', ['CAM'], 83),
        ('Milenko Ačimovič', ['CM'], 80),
        ('Nastja Čeh', ['CM'], 79),
        ('Robert Koren', ['CM'], 78),
        ('Marinko Galič', ['ST'], 77),
        ('Sebastjan Cimirotič', ['LW'], 78),
        ('Aleksander Knavs', ['CB'], 77),
        ('Amir Karič', ['LB'], 77),
        ('Djordje Čanak', ['RB'], 75),
        ('Ermin Šiljak', ['ST'], 77),
        ('Brane Oblak', ['CDM'], 76),
    ]),
    ('South Africa', 2002, [
        ('Hans Vonk', ['GK'], 76),
        ('Benni McCarthy', ['ST'], 82),
        ('Shaun Bartlett', ['ST'], 80),
        ('Mark Fish', ['CB'], 80),
        ('Lucas Radebe', ['CB'], 82),
        ('Quinton Fortune', ['LW'], 81),
        ('Sibusiso Zuma', ['RW'], 79),
        ('John Moshoeu', ['CM'], 79),
        ('Pierre Issa', ['CB'], 77),
        ('Delron Buckley', ['LM'], 77),
        ('Siyabonga Nomvethe', ['LW'], 78),
        ('Mbulelo Mabizela', ['RB'], 76),
        ('Teboho Molefe', ['CDM'], 75),
        ('Doctor Khumalo', ['CAM'], 77),
        ('Bradley Carnell', ['CM'], 76),
        ('Elrio van Heerden', ['CB'], 75),
    ]),
    ('South Korea', 2002, [
        ('Lee Woon-jae', ['GK'], 82),
        ('Ahn Jung-hwan', ['ST'], 83),
        ('Park Ji-sung', ['CM'], 82),
        ('Hong Myung-bo', ['CB'], 85),
        ('Hwang Sun-hong', ['ST'], 82),
        ('Yoo Sang-chul', ['CDM'], 82),
        ('Kim Nam-il', ['CM'], 80),
        ('Choi Jin-cheul', ['CB'], 80),
        ('Song Chong-gug', ['RB'], 80),
        ('Lee Young-pyo', ['LB'], 82),
        ('Seol Ki-hyeon', ['RW'], 80),
        ('Lee Eul-yong', ['CM'], 79),
        ('Choi Yong-soo', ['CAM'], 80),
        ('Park Hang-seo', ['CDM'], 78),
        ('Kim Tae-young', ['CB'], 78),
        ('Choi Sung-yong', ['GK'], 78),
    ]),
    ('Spain', 2002, [
        ('Iker Casillas', ['GK'], 86),
        ('Raúl', ['ST'], 90),
        ('Fernando Morientes', ['ST'], 86),
        ('Fernando Hierro', ['CB'], 86),
        ('Xavi', ['CM'], 83),
        ('Gaizka Mendieta', ['RM'], 84),
        ('Míchel Salgado', ['RB'], 81),
        ('Carles Puyol', ['CB'], 84),
        ('Ivan Helguera', ['CB'], 83),
        ('Juanfran', ['LB'], 79),
        ('Rubén Baraja', ['CM'], 81),
        ('Fernando Sanz', ['CDM'], 78),
        ('Valdés', ['GK'], 80),
        ('Joaquín', ['RW'], 81),
        ('David Albelda', ['CDM'], 80),
        ('Albert Luque', ['LW'], 79),
    ]),
    ('Sweden', 2002, [
        ('Magnus Hedman', ['GK'], 81),
        ('Henrik Larsson', ['ST'], 87),
        ('Zlatan Ibrahimović', ['ST'], 82),  # debut WC, 20 years old
        ('Freddie Ljungberg', ['CM'], 85),
        ('Andreas Andersson', ['RW'], 79),
        ('Niclas Alexandersson', ['RM'], 80),
        ('Olof Mellberg', ['CB'], 83),
        ('Patrik Andersson', ['CB'], 82),
        ('Teddy Lucic', ['LB'], 79),
        ('Roland Nilsson', ['RB'], 79),
        ('Anders Svensson', ['CM'], 81),
        ('Mikael Nilsson', ['RB'], 77),
        ('Marcus Allbäck', ['ST'], 79),
        ('Johan Mjällby', ['CB'], 79),
        ('Tobias Linderoth', ['CDM'], 78),
        ('Kim Källström', ['CM'], 78),
    ]),
    ('Tunisia', 2002, [
        ('Ali Boumnijel', ['GK'], 78),
        ('Radhi Jaïdi', ['CB'], 80),
        ('Hatem Trabelsi', ['RB'], 81),
        ('Riadh Bouazizi', ['CM'], 79),
        ('Adel Sellimi', ['RW'], 79),
        ('Skander Souayah', ['ST'], 78),
        ('Karim Haggui', ['CB'], 77),
        ('Khaled Badra', ['CM'], 77),
        ('Hamed Nasr', ['CDM'], 76),
        ('Sirajeddine Chihi', ['LB'], 76),
        ('Mehdi Nafti', ['CM'], 78),
        ('Imed Ben Younes', ['LW'], 76),
    ]),
    ('USA', 2002, [
        ('Brad Friedel', ['GK'], 82),
        ('Landon Donovan', ['CAM'], 82),
        ('Brian McBride', ['ST'], 81),
        ('Claudio Reyna', ['CM'], 82),
        ('DaMarcus Beasley', ['LW'], 81),
        ('Cobi Jones', ['LW'], 79),
        ('Carlos Bocanegra', ['CB'], 79),
        ('Eddie Pope', ['CB'], 80),
        ('Josh Wolff', ['ST'], 78),
        ('John O\'Brien', ['CM'], 79),
        ('Earnie Stewart', ['ST'], 79),
        ('Tony Sanneh', ['RB'], 77),
        ('Jeff Agoos', ['LB'], 77),
        ('Pablo Mastroeni', ['CDM'], 78),
        ('Kasey Keller', ['GK'], 81),
        ('Tim Howard', ['GK'], 79),
    ]),
    ('Uruguay', 2002, [
        ('Fabián Carini', ['GK'], 77),
        ('Álvaro Recoba', ['LW'], 84),
        ('Darío Silva', ['ST'], 83),
        ('Diego Forlán', ['ST'], 83),
        ('Enzo Francescoli', ['CAM'], 82),  # veteran
        ('Gustavo Poyet', ['CM'], 82),
        ('Carlos Valdez', ['CB'], 78),
        ('Paolo Montero', ['CB'], 82),
        ('Marcelo Romero', ['LB'], 76),
        ('Mario Regueiro', ['CM'], 78),
        ('Nicolás Olivera', ['CM'], 79),
        ('Jorge García', ['RB'], 76),
        ('Andrés Scotti', ['CB'], 79),
        ('Richard Morales', ['ST'], 77),
        ('Sebastián Abreu', ['ST'], 79),
        ('Federico Magallanes', ['CM'], 76),
    ]),
]

add_nations(OLD_PATH, 'WC', SQUADS)

# Summary
import json
data = json.load(open(OLD_PATH))
for year in [1986, 1990, 1994, 1998, 2002]:
    nations = sorted(set(p['nation'] for p in data if p['year'] == year))
    print(f'{year}: {len(nations)} nations')
